version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis
    db:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_DATABASE: 'mehdi'
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: ''
          MYSQL_ROOT_PASSWORD: ''
        ports:
            - "3306:3306"
        expose:
            - '3306'
        volumes:
            - my-db:/var/lib/mysql

volumes:
  my-db:
  .:
