version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - flask:/code
        depends_on:
            - redis
            - mysql
        networks: 
            - flask

    redis:
        image: redis
        networks:
            - flask


    mysql:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_DATABASE: 'webview'
          MYSQL_USER: 'app'
          MYSQL_PASSWORD: '123456'
          MYSQL_ROOT_PASSWORD: 'DADcsanjabhsdfa'
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - flask
            

volumes:
  flask:
    driver: local
  mysql:
    driver: local

networks:
    flask:
